name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Make sure unit tests succeed
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "githubaction@gmail.com"
        uv run pytest
    - name: Build
      run: |
        uv build
    # See https://docs.pypi.org/trusted-publishers/using-a-publisher/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Deploy mkdocs site
      run: | 
        uv run mkdocs gh-deploy --force
