name: Unit tests
on: [pull_request]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Generate coverage report
      run: |
        uv run pytest --cov=mkdocs_git_authors_plugin --cov-report=xml